const container = document.querySelector(".container-fluid");
const formMain = document.createElement("form");
formMain.className = "form";
const divUser = document.createElement("div");
const labelUser = document.createElement("label");

const inputUser = document.createElement("input");
inputUser.placeholder = "UserName...";
inputUser.id = "inputUser";
labelUser.htmlFor = "inputUser";
divUser.className = "mb-3";
labelUser.className = "form-label";
inputUser.className = "form-control";
inputUser.type = "text";
divUser.append(labelUser);
divUser.append(inputUser);
labelUser.append("UserName:");
const divPass = document.createElement("div");
const labelPass = document.createElement("label");
const inputPass = document.createElement("input");
inputPass.placeholder = "password...";
labelPass.append("Password:");
inputPass.type = "password";
inputPass.id = "inputPass";
labelPass.htmlFor = "inputPass";
labelPass.className = "form-label";
inputPass.className = "form-control";
divPass.className = "mb-3";
divPass.append(labelPass);
divPass.append(inputPass);
const divBtn = document.createElement("div");
const btnSumbit = document.createElement("button");
divBtn.className = "col-12";
btnSumbit.type = "submit";
btnSumbit.className = "btn btn-primary";
btnSumbit.innerHTML = "Login";
divBtn.append(btnSumbit);
formMain.append(divUser);
formMain.append(divPass);
formMain.append(divBtn);
container.append(formMain);
